### ISSUE TITLE
CSV出力エラー

### ISSUE THREAD

**Issue by tarusoopy** [hiracy/serverspec-runner#48]
初めて利用させていただいています。  
CSV出力させようと `-t csv` オプションで実行したところ、以下のエラーが出ました。ruby勉強し始めたばかりで、Rakefile見てもわからなかったのですが、原因に心当たりありますでしょうか。  
CSV以外(ASCII Art、md)は出力できています。

- 環境
```
$ cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)
$ ruby -v
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]
$ which ruby
/opt/rh/rh-ruby25/root/usr/bin/ruby
```

- ログ
```
...(serverspec original log)

description,,,,result
vtm/base@vtm01(192.168.120.2),,,,
,File "/var/log/vario",,,
,,is expected to be directory,,OK
,,is expected to be owned by "root",,OK
,,is expected to be grouped into "root",,OK
,,is expected to be mode 755,,OK
,File "/etc/sysconfig/network-scripts/route-eth0",,,
,,is expected to be file,,OK
,,is expected to be owned by "root",,OK
,,is expected to be grouped into "root",,OK
,,is expected to be mode 644,,OK
,Routing Table,,,
Traceback (most recent call last):
        28: from /home/h.nakano/bin/serverspec-runner:23:in `<main>'
        27: from /home/h.nakano/bin/serverspec-runner:23:in `load'
        26: from /home/h.nakano/.gem/ruby/gems/serverspec-runner-1.3.8/bin/serverspec-runner:98:in `<top (required)>'
        25: from /home/h.nakano/.gem/ruby/gems/rake-13.0.3/lib/rake/task.rb:188:in `invoke'
        24: from /home/h.nakano/.gem/ruby/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
        23: from /opt/rh/rh-ruby25/root/usr/share/ruby/monitor.rb:226:in `mon_synchronize'
        22: from /home/h.nakano/.gem/ruby/gems/rake-13.0.3/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
        21: from /home/h.nakano/.gem/ruby/gems/rake-13.0.3/lib/rake/task.rb:241:in `invoke_prerequisites'
        20: from /home/h.nakano/.gem/ruby/gems/rake-13.0.3/lib/rake/task.rb:241:in `each'
        19: from /home/h.nakano/.gem/ruby/gems/rake-13.0.3/lib/rake/task.rb:243:in `block in invoke_prerequisites'
        18: from /home/h.nakano/.gem/ruby/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
        17: from /opt/rh/rh-ruby25/root/usr/share/ruby/monitor.rb:226:in `mon_synchronize'
        16: from /home/h.nakano/.gem/ruby/gems/rake-13.0.3/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
        15: from /home/h.nakano/.gem/ruby/gems/rake-13.0.3/lib/rake/task.rb:241:in `invoke_prerequisites'
        14: from /home/h.nakano/.gem/ruby/gems/rake-13.0.3/lib/rake/task.rb:241:in `each'
        13: from /home/h.nakano/.gem/ruby/gems/rake-13.0.3/lib/rake/task.rb:243:in `block in invoke_prerequisites'
        12: from /home/h.nakano/.gem/ruby/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
        11: from /opt/rh/rh-ruby25/root/usr/share/ruby/monitor.rb:226:in `mon_synchronize'
        10: from /home/h.nakano/.gem/ruby/gems/rake-13.0.3/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
         9: from /home/h.nakano/.gem/ruby/gems/rake-13.0.3/lib/rake/task.rb:281:in `execute'
         8: from /home/h.nakano/.gem/ruby/gems/rake-13.0.3/lib/rake/task.rb:281:in `each'
         7: from /home/h.nakano/.gem/ruby/gems/rake-13.0.3/lib/rake/task.rb:281:in `block in execute'
         6: from /home/h.nakano/.gem/ruby/gems/serverspec-runner-1.3.8/Rakefile:240:in `block (2 levels) in <top (required)>'
         5: from /opt/rh/rh-ruby25/root/usr/share/ruby/csv.rb:1141:in `foreach'
         4: from /opt/rh/rh-ruby25/root/usr/share/ruby/csv.rb:1289:in `open'
         3: from /opt/rh/rh-ruby25/root/usr/share/ruby/csv.rb:1142:in `block in foreach'
         2: from /opt/rh/rh-ruby25/root/usr/share/ruby/csv.rb:1764:in `each'
         1: from /home/h.nakano/.gem/ruby/gems/serverspec-runner-1.3.8/Rakefile:241:in `block (3 levels) in <top (required)>'
/home/h.nakano/.gem/ruby/gems/serverspec-runner-1.3.8/Rakefile:241:in `*': negative argument (ArgumentError)
```

**Comment by hiracy** [comment]
こんにちは
こちらシナリオファイルを見せて頂くことは可能でしょうか。

`pad_comma = ',' * (maxrows - r[0].split(',').length)`

この箇所にて(maxrows - r[0].split(',').length)が負数になっているのでシナリオファイル内のテスト結果にてカンマが入っている可能性があります。
